services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitxodev-portfolio
    restart: always
    networks:
      - nginx-proxy_default

networks:
  nginx-proxy_default:
    external: true
